language: java

jdk:
  - openjdk7

sudo: false

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
# matrix-start
    - R_CHECK_PACKAGES=""
# matrix-end

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - "export DISPLAY=:99.0"
  - "export PATH=$PATH:$HOME/bin"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
    - gcc
    - g++
    - gfortran
    - libblas-dev
    - liblapack-dev
    - tcl8.5-dev
    - tk8.5-dev
    - bison
    - groff-base
    - libncurses5-dev
    - libreadline-dev
    - debhelper
    - texi2html
    - texinfo
    - libbz2-dev
    - liblzma-dev
    - libpcre3-dev
    - xdg-utils
    - zlib1g-dev
    - libpng-dev
    - libjpeg-dev
    - libx11-dev
    - libxt-dev
    - x11proto-core-dev
    - libpango1.0-dev
    - libcairo2-dev
    - libtiff5-dev
    - xvfb
    - xauth
    - xfonts-base
    - texlive-base
    - texlive-latex-base
    - texlive-generic-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-extra-utils
    - texlive-latex-recommended
    - texlive-latex-extra
    - default-jdk

cache:
  directories:
  - $HOME/bin
  - $HOME/R-base

# summon crandalf!
script:
  - ./inst/scripts/install-r
  - ./inst/scripts/install-pandoc
  - ./inst/scripts/crandalf
  - "[ $TRAVIS_BRANCH == master ] && R CMD check --no-manual ../crandalf_*.tar.gz || true"
