language: c

sudo: false

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
# matrix-start
    - R_CHECK_PACKAGES="additivityTests ADPclust agridat alm AncestryMapper anim.plots Anthropometry aoos aop apex aplore3 apsimr ArgumentCheck ARPobservation aRxiv ASMap aSPU assertive assertr atsd attribrisk babar BACA BayesFactor bayesGDS BayesSingleSub bbmle bcpa bdscale BEQI2 BIGDAWG bio3d biogas biom biomartr biorxivr bizdays BlandAltmanLeh blocksdesign bnclassify bnstruct bold boostr BrailleR broom BTYD captioner caretEnsemble caRpools cati causalsens Causata cda checkmate checkpoint ChemoSpec chipPCR CHNOSZ"
    - R_CHECK_PACKAGES="choroplethr circlize classyfire clifro climwin ClustVarLV coala coenocliner confidence COPASutils corrgram corrplot cosinor covr cowplot credule crimelinkage Crossover crunch ctmm ctsem curl D2C d3heatmap DAAG Dark dataRetrieval datastepr data.tree decisionSupport decode decompr dendextend dendsort denovolyzeR desiR devtools diagonals DiagrammeR discreteRV DNAprofiles doRNG dotwhisker dpcR dplR dplyr drat DT DVHmetrics dynsim EasyHTMLReport Ecdat ecoengine EcoSimR EEM EFDR ega EGRET"
    - R_CHECK_PACKAGES="eHOF elastic EMbC enigma enpls ensurer EpiBayes EpiModel ESGtoolkit eurostat excel.link ExomeDepth expp ExtDist FAOSTAT fastR fgpt flexsurv flows forestplot formatR fpCompare fslr fulltext FuzzyNumbers gamclass gapmap GenCAT gender geojsonio GetoptLong ggdendro ggenealogy ggExtra ggplot2 ggRandomForests ggthemes ggvis gistr glarma glmm glmnet GlobalOptions gmailr GMCM gMCP Gmisc googlesheets googleVis GOplot gridExtra gsDesign HarmonicRegression haven hazus hddplot heatmap3 HHG"
    - R_CHECK_PACKAGES="hierband HighDimOut highr Hmisc hpoPlot hSDM htmltab htmlTable htmltools htmlwidgets httr HWxtest HydeNet hysteresis iBUGS icd9 ifaTools import inferference interAdapt intergraph internetarchive interplot iptools ISOpureR itsadug JacobiEigen jiebaR js jsonlite jtrans KFAS kfigr kitagawa Kmisc knitcitations knitLatex knitrBootstrap knockoff kyotil latex2exp lawn lazyeval lctools LDAvis leaflet learningr lfe lifecontingencies liftr likelihoodAsy linbin lineup lintr list lme4 LocFDRPois"
    - R_CHECK_PACKAGES="LogisticDx longpower loo loopr ltbayes lubridate lucid magrittr MALDIquant MALDIquantForeign manifestoR mapmisc markdown markophylo markovchain MarkowitzR matrixStats MazamaSpatialUtils mbbefd mclust mcmcse mcprofile medicalrisk megaptera memgene merTools metafolio metaMix metricsgraphics mi miniCRAN MInt mirt mirtCAT miscset mixedMem mkin mldr mlr MM2S MM2Sdata mongolite monitoR moonBook MortalitySmooth mosaic mountainplot mplot MPSEM MPTinR multiplex MVN mvnfast mvtboost mwaved mycor myTAI"
    - R_CHECK_PACKAGES="nCal ncappc ndtv neotoma nestedRanksTest networkD3 networkreporting neuroim nicheROVER NlsyLinks NMF NNTbiomarker nonlinearTseries NORTARA nplr nullabor OasisR olctools OLScurve opencpu openssl openxlsx optiRum OrgMassSpecR OutbreakTools packcircles packrat pacman pairsD3 palr pander PANICr ParallelForest params patchDVI patchSynctex pathdiagram pbo pca3d pcaBootPlot PDQutils pez PGRdup phangorn phonenumber phylobase physiology pitchRx pixiedust planar plotROC plspm pmc pmmlTransformations polidata pollstR PopGenReport"
    - R_CHECK_PACKAGES="poppr poweRlaw PP prospectr PSAboot psd psData pt pumilioR pvar pweight pxweb qdap qicharts qlcMatrix qmethod QoLR qqman quanteda quipu R2admb R6 radiant raincpc rainfreq randomizr rbhl rbison RBitly rchallenge rclinicaltrials Rcmdr RcmdrPlugin.MA RCMIP5 RcppFaddeeva rcrossref Rd2roxygen rddtools Rdistance RDML rDVR readr rebird reconstructr recosystem REDCapR RefManageR refset rentrez repijson repo reports repra rerddap REST reval RevEcoR"
    - R_CHECK_PACKAGES="rex RGA rgauges rgbif rgeolocate rgl rglobi rhandsontable rio rite rivr rjade RJafroc rmarkdown rmongodb rnbn RNeXML rngtools rNMF rnoaa RODBCext rotations rotl roxygen2 rpf rplexos rplos rprime rprintf RRreg R.rsp rsatscan RSelenium rsnps RSNPset rspa rsunlight rtable rtype rucm rUnemploymentData runjags rvertnet rvest rWBclimate rYoutheria sadists saeSim samplesize4surveys satellite scatterD3 SCGLR schumaker scrm sdcMicro SDR secr"
    - R_CHECK_PACKAGES="secrdesign secrlinear sequences seroincidence servr settings SharpeR shiny shinyjs shinystan shotGroups signalHsmm simcausal simmr SIMMS simPH simTool skellam sla SLOPE smacof smcfcs snht snplist snp.plotter snpStatsWriter softImpute solr SOMbrero sorvi sotkanet soundecology spacetime SpaDES sparseHessianFD sparseMVN SpatialPosition spca spcadjust spdep spdynmod spocc spoccutils sprinter spThin ss3sim statar StMoMo stringgaussnet stringr survSNP svgPanZoom svSweave SwarmSVM sweidnumbr synlik systemicrisk"
    - R_CHECK_PACKAGES="syuzhet tableone tagcloud taxize tcR tester texmex textreg threejs TiddlyWikiR tidyjson tidyr tigerstats tikzDevice tmap tmle.npvi tmod TopKLists traits transcribeR trimr trip trustOptim TSMining tufterhandout turner TurtleGraphics ucbthesis UNF UpSetR urltools USAboundaries userfriendlyscience vartors vdg vdmR vegdata visNetwork WaterML Wats webreadr WeightedCluster whoapi WikidataR wikipediatrend WikipediR wildlifeDI wiod WiSEBoot wrassp wsrf WufooR xgboost XNomial yakmoR zooaRch ztable"
    - R_CHECK_PACKAGES="DLMtool hot.deck HiveR pkgmaker"
# matrix-end

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - "export DISPLAY=:99.0"
  - "export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - libmpfr-dev
    - openjdk-7-jdk
    - r-base-dev
    - r-recommended
    - texinfo

cache:
  directories:
  - $HOME/bin
  - $HOME/R
  - $HOME/texlive

install:
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e 'devtools::install_deps(dep = TRUE)'

# summon crandalf!
script:
  - ./inst/scripts/install-texlive
  - R -e "sapply(.libPaths(), list.files, simplify=F)"
  - ./inst/scripts/install-pandoc
  - cd ..; R CMD build crandalf && R CMD INSTALL crandalf_*.tar.gz; cd crandalf
  - ./inst/scripts/crandalf
  - "[ $TRAVIS_BRANCH == master ] && R CMD check --no-manual ../crandalf_*.tar.gz || true"
